# Generated by Django 4.0.1 on 2023-01-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='stock'),
        ),
    ]
